// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzMoY6JLVp8IGojF0eQyviFI75P_xMTbM',
    appId: '1:807664586594:web:f6a843d60be2923308663b',
    messagingSenderId: '807664586594',
    projectId: 'mobilegarage-e741f',
    authDomain: 'mobilegarage-e741f.firebaseapp.com',
    storageBucket: 'mobilegarage-e741f.firebasestorage.app',
    measurementId: 'G-VZYGM5KJDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBlVJyFXAnu7sv9tFNnGc0AXwX2OJRjP8',
    appId: '1:807664586594:android:cbb180cf4f4b348108663b',
    messagingSenderId: '807664586594',
    projectId: 'mobilegarage-e741f',
    storageBucket: 'mobilegarage-e741f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaN2WKk568DPjf4DiJrY3Vghd5aMKUBdU',
    appId: '1:807664586594:ios:4cca3119b4b5f9ea08663b',
    messagingSenderId: '807664586594',
    projectId: 'mobilegarage-e741f',
    storageBucket: 'mobilegarage-e741f.firebasestorage.app',
    iosBundleId: 'com.tritec.mobilegarage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaN2WKk568DPjf4DiJrY3Vghd5aMKUBdU',
    appId: '1:807664586594:ios:4cca3119b4b5f9ea08663b',
    messagingSenderId: '807664586594',
    projectId: 'mobilegarage-e741f',
    storageBucket: 'mobilegarage-e741f.firebasestorage.app',
    iosBundleId: 'com.tritec.mobilegarage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzMoY6JLVp8IGojF0eQyviFI75P_xMTbM',
    appId: '1:807664586594:web:f28d22b79b07528e08663b',
    messagingSenderId: '807664586594',
    projectId: 'mobilegarage-e741f',
    authDomain: 'mobilegarage-e741f.firebaseapp.com',
    storageBucket: 'mobilegarage-e741f.firebasestorage.app',
    measurementId: 'G-CFKDS1P25G',
  );

}