// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxDiZkYIUuE3XWbBH7PNNKHrF_J3MOeqA',
    appId: '1:457022457516:web:21ab486487c42244e80109',
    messagingSenderId: '457022457516',
    projectId: 'garage-67679',
    authDomain: 'garage-67679.firebaseapp.com',
    storageBucket: 'garage-67679.appspot.com',
    measurementId: 'G-PZRGZCK5S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl1FsCqYfDAncFFFtf_VLMrjAWSepRNZ8',
    appId: '1:457022457516:android:d82102f158303da3e80109',
    messagingSenderId: '457022457516',
    projectId: 'garage-67679',
    storageBucket: 'garage-67679.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2b71SoxGWEb3sInQw3u6isnAbVOnJnVE',
    appId: '1:457022457516:ios:85847c4cc1312e3fe80109',
    messagingSenderId: '457022457516',
    projectId: 'garage-67679',
    storageBucket: 'garage-67679.appspot.com',
    iosBundleId: 'com.tritec.mobilegarage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2b71SoxGWEb3sInQw3u6isnAbVOnJnVE',
    appId: '1:457022457516:ios:85847c4cc1312e3fe80109',
    messagingSenderId: '457022457516',
    projectId: 'garage-67679',
    storageBucket: 'garage-67679.appspot.com',
    iosBundleId: 'com.tritec.mobilegarage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxDiZkYIUuE3XWbBH7PNNKHrF_J3MOeqA',
    appId: '1:457022457516:web:6fb7fe3679a1b76fe80109',
    messagingSenderId: '457022457516',
    projectId: 'garage-67679',
    authDomain: 'garage-67679.firebaseapp.com',
    storageBucket: 'garage-67679.appspot.com',
    measurementId: 'G-EQZ8Q7Y85J',
  );
}
