// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFspOpY70fGPnHH-bkwz4OFU1ZI5zzjJ4',
    appId: '1:323733471662:web:e5c5efb662d5d57c04483f',
    messagingSenderId: '323733471662',
    projectId: 'mobile-garage-b16a3',
    authDomain: 'mobile-garage-b16a3.firebaseapp.com',
    storageBucket: 'mobile-garage-b16a3.firebasestorage.app',
    measurementId: 'G-15VHBCYYMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwf8uu4aqcldQtSKLPxfLdXCCf2G3oXTM',
    appId: '1:323733471662:android:0e93a41261ace1a804483f',
    messagingSenderId: '323733471662',
    projectId: 'mobile-garage-b16a3',
    storageBucket: 'mobile-garage-b16a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRT9wNcCIozIiLEYYDxIB-o8Gfo80oaoM',
    appId: '1:323733471662:ios:628f43df1b83243d04483f',
    messagingSenderId: '323733471662',
    projectId: 'mobile-garage-b16a3',
    storageBucket: 'mobile-garage-b16a3.firebasestorage.app',
    iosBundleId: 'com.tritec.mobilegarage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRT9wNcCIozIiLEYYDxIB-o8Gfo80oaoM',
    appId: '1:323733471662:ios:628f43df1b83243d04483f',
    messagingSenderId: '323733471662',
    projectId: 'mobile-garage-b16a3',
    storageBucket: 'mobile-garage-b16a3.firebasestorage.app',
    iosBundleId: 'com.tritec.mobilegarage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFspOpY70fGPnHH-bkwz4OFU1ZI5zzjJ4',
    appId: '1:323733471662:web:928523b667b5d37104483f',
    messagingSenderId: '323733471662',
    projectId: 'mobile-garage-b16a3',
    authDomain: 'mobile-garage-b16a3.firebaseapp.com',
    storageBucket: 'mobile-garage-b16a3.firebasestorage.app',
    measurementId: 'G-38HGX9D8BC',
  );
}
